vms = {
  vm-gw = {
    vmid            = 101
    cores           = 2
    memory          = 2048
    disk_size_gb    = 16
    machine         = "q35"
    boot_order      = ["virtio0"]
    keyboard_layout = "en-us"
    scsi_hardware   = "virtio-scsi-pci"
    serial_console  = false
    cloud_init_user = "root"
    root_discard    = "on"
    extra_disks     = []
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:b5:da:e2"
      vlan_id = 20
    }]
  }

  vm-media = {
    vmid            = 102
    cores           = 4
    memory          = 8192
    disk_size_gb    = 164
    machine         = "q35"
    boot_order      = ["virtio0"]
    keyboard_layout = "en-us"
    scsi_hardware   = "virtio-scsi-single"
    serial_console  = false
    cloud_init_user = "shakir"
    root_discard    = "on"
    extra_disks = [{
      interface         = "scsi1"
      path_in_datastore = "/dev/disk/by-id/ata-Samsung_SSD_860_PRO_1TB_S42NNF0K301218P"
      backup            = false
      discard           = "on"
      ssd               = true
    }]
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:bb:ac:8b"
      vlan_id = 20
    }]
  }

  vm-storage = {
    vmid            = 103
    cores           = 2
    memory          = 2048
    disk_size_gb    = 16
    machine         = ""
    boot_order      = ["virtio0"]
    keyboard_layout = "en-us"
    scsi_hardware   = "virtio-scsi-pci"
    serial_console  = false
    root_discard    = "on"
    extra_disks = [
      {
        interface         = "scsi1"
        path_in_datastore = "/dev/disk/by-id/ata-ST16000NE000-2RW103_ZL2F1CAK"
        backup            = true
        discard           = "ignore"
        ssd               = false
      },
      {
        interface         = "scsi2"
        path_in_datastore = "/dev/disk/by-id/ata-ST16000NE000-2RW103_ZL2F1CAP"
        backup            = true
        discard           = "ignore"
        ssd               = false
      },
    ]
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:ec:74:e6"
      vlan_id = 20
    }]
  }

  vm-sensitive = {
    vmid            = 104
    cores           = 2
    memory          = 6144
    disk_size_gb    = 16
    machine         = "q35"
    boot_order      = ["virtio0"]
    keyboard_layout = "en-us"
    scsi_hardware   = "virtio-scsi-pci"
    serial_console  = false
    root_discard    = "on"
    extra_disks     = []
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:6d:92:b4"
      vlan_id = 20
    }]
  }

  vm-apps = {
    vmid           = 105
    cores          = 2
    memory         = 3072
    disk_size_gb   = 16
    machine        = "q35"
    boot_order     = []
    description    = " generated by NixOS"
    scsi_hardware  = "virtio-scsi-single"
    serial_console = true
    root_discard   = "on"
    extra_disks    = []
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:ad:85:c4"
      vlan_id = 20
    }]
  }

  vm-monitoring = {
    vmid           = 106
    cores          = 2
    memory         = 4096
    disk_size_gb   = 64
    machine        = ""
    boot_order     = []
    description    = " generated by NixOS"
    scsi_hardware  = "virtio-scsi-single"
    serial_console = true
    root_discard   = "ignore"
    extra_disks    = []
    nics = [{
      bridge  = "vmbr0"
      mac     = "bc:24:11:9a:3f:06"
      vlan_id = 20
    }]
  }
}
