title: Homelab
description: Media & automation
theme: dark

fullWidth: true
maxGroupColumns: 5

target: _blank

headerStyle: boxed
iconStyle: theme
statusStyle: dot

language: en-GB

layout:
  Media:
    tab: Home
    style: column

  Requests:
    tab: Home
    style: column

  Automation:
    tab: Home
    style: column

  Infrastructure:
    tab: Home
    style: column

  Monitoring:
    tab: Home
    style: column

  Personal:
    tab: Personal
    style: row
    columns: 3
